version: "3"

services:
  web:
    container_name: www
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
  db:
    container_name: database
    image: mysql
    build: .
    command: [ "--default-authentication-plugin=mysql_native_password"]
    volumes:
      - "./.data/:/var/lib/mysql"
      - "./init/:/docker-entrypoint-initdb.d/"
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"